#!/bin/bash

mkdir -p ./done/_COURSERA/$1
cp "template.py" "./done/_COURSERA/$1/$1_run.py"
touch "./done/_COURSERA/$1/$1.py"
touch "./done/_COURSERA/$1/input.txt"
open "./done/_COURSERA/$1/"
open "./done/_COURSERA/$1/input.txt"